version: '2.3'

services:
  postgres-server:
    build: ./database-container
    networks:
      - mybridge
    environment:
     - POSTGRES_USER=driver
     - POSTGRES_PASSWORD=verylongandsecurerootpassword
     - POSTGRES_DB=prod

  portal:
    build: ./portal-container/IcePortalServer
    networks:
      - mybridge
    depends_on:
      - postgres-server

  seedbox:
    build: ./seedbox-container/SeederServer
    networks:
      - mybridge
    ports:
      - "29200:29200"
    depends_on:
      - portal

  clientmanager:
    build: ./cmanager-container/ClientManager
    networks:
      - mybridge
    ports:
      - "80:80"
    depends_on:
      - seedbox

networks:
  mybridge:
