version: '2.3'

services:
  postgres-server:
    image: eu.gcr.io/groupj-179216/fq-db:rc2
    build: ./database-container
    networks:
      - mybridge
    environment:
     - POSTGRES_USER=driver
     - POSTGRES_PASSWORD=verylongandsecurerootpassword
     - POSTGRES_DB=prod

  seedbox:
    image: eu.gcr.io/groupj-179216/fq-seedbox:rc2
    build: ./seedbox-container/SeederServer
    networks:
      - mybridge
    ports:
      - "29200:29200"
    depends_on:
      - postgres-server

  clientmanager:
    image: eu.gcr.io/groupj-179216/fq-cmanager:rc2
    build: ./cmanager-container/ClientManager
    networks:
      - mybridge
    ports:
      - "8080:8080"
    depends_on:
      - seedbox

networks:
  mybridge:
