version: '2.3'

services:
  postgres-server:
    image: eu.gcr.io/${PROJECT_ID}/fq-db:rc2
    build: ./database-container
    networks:
      - mybridge
    environment:
     - POSTGRES_USER=driver
     - POSTGRES_PASSWORD=verylongandsecurerootpassword
     - POSTGRES_DB=prod

  portal:
    image: eu.gcr.io/${PROJECT_ID}/fq-portal:rc2
    build: ./portal-container/IcePortalServer
    networks:
      - mybridge
    depends_on:
      - postgres-server

  seedbox:
    image: eu.gcr.io/${PROJECT_ID}/fq-seedbox:rc2
    build: ./seedbox-container/SeederServer
    networks:
      - mybridge
    ports:
      - "29200:29200"
    depends_on:
      - portal

  clientmanager:
    image: eu.gcr.io/${PROJECT_ID}/fq-cmanager:rc2
    build: ./cmanager-container/ClientManager
    networks:
      - mybridge
    ports:
      - "8080:8080"
    depends_on:
      - seedbox

networks:
  mybridge:
