apiVersion: v1
kind: Service
metadata:
  name: cmanager
  labels:
    app: cmanager
spec:
  type: LoadBalancer
  loadBalancerIP: "35.195.218.215"
  ports:
  - port: 8080
  selector:
    app: cmanager
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cmanager
    spec:
      containers:
      - name: clientmanager
        image: eu.gcr.io/groupj-179216/fq-cmanager:rc2
        env:
        - name: CMANAGER_IP
          value: "35.195.218.215"
        ports:
        - containerPort: 8080
