apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    app: portal
spec:
  type: ClusterIP
  ports:
  - port: 8081
  selector:
    app: portal
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: portal
        image: eu.gcr.io/groupj-179216/fq-portal:rc2
        ports:
          - containerPort: 8081
