apiVersion: v1
kind: Service
metadata:
  name: seedbox
  labels:
    app: seedbox
spec:
  type: LoadBalancer
  loadBalancerIP: "35.187.185.209"
  ports:
  - port: 29200
    name: sockets
  - port: 8082
    name: ice
  selector:
    app: seedbox
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: seedbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: seedbox
    spec:
      containers:
      - name: seedbox
        image: eu.gcr.io/groupj-179216/fq-seedbox:rc2
        env:
        - name: SEEDBOX_IP
          value: "35.187.185.209"
        ports:
          - containerPort: 29200
            name: sockets
          - containerPort: 8082
            name: ice
        volumeMounts:
            - name: seedbox-persistent-storage
              mountPath: /var/lib/seedbox
      volumes:
        - name: seedbox-persistent-storage
          gcePersistentDisk:
            pdName: seedbox-disk
            fsType: ext4
