apiVersion: v1
kind: Service
metadata:
  name: postgres-server
  labels:
    app: postgres-server
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: postgres-server
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-server
    spec:
      containers:
      - name: postgres-server
        image: eu.gcr.io/groupj-179216/fq-db:rc1
        env:
        - name: POSTGRES_USER
          value: "driver"
        - name: POSTGRES_PASSWORD
          value: "verylongandsecurerootpassword"
        - name: POSTGRES_DB
          value: "prod"
        ports:
          - containerPort: 5432
