apiVersion: v1
kind: Service
metadata:
  name: seedbox
  labels:
    app: seedbox
spec:
  type: LoadBalancer
  ports:
  - port: 29200
    name: sockets
  - port: 8082
    name: ice
  selector:
    app: seedbox
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: seedbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: seedbox
    spec:
      containers:
      - name: seedbox
        image: eu.gcr.io/groupj-179216/fq-seedbox:rc1
        ports:
          - containerPort: 29200
            name: sockets
          - containerPort: 8082
            name: ice
